name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build release APK
        run: bash ./gradlew assembleRelease
      - name: check folder
        run: ls /home/runner/work/LibreMessenger/LibreMessenger/briar-android/build/outputs/apk/official/release
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: briar-android/build/outputs/apk/official/release/libre-release.apk
